# Generated by Django 3.2.16 on 2023-01-31 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('flat', 'Flat'), ('townhouse', 'Townhouse'), ('villa', 'Villa'), ('residential hosuing estate', 'Residential Housing Estate'), ('country property', 'Country Property'), ('bungalow', 'Bungalow')], max_length=30)),
                ('province', models.CharField(choices=[('huelva', 'Huelva'), ('sevilla', 'Sevilla'), ('cadiz', 'Cadiz'), ('cordoba', 'Cordoba'), ('granada', 'Granada'), ('malaga', 'Malaga'), ('jaen', 'Jaen'), ('almeria', 'Almeria')], max_length=20)),
                ('street', models.CharField(blank=True, max_length=40, null=True)),
                ('municipality', models.CharField(max_length=60)),
                ('post_code', models.CharField(max_length=5)),
                ('price', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('bedroom_count', models.PositiveIntegerField()),
                ('bathrooms_count', models.PositiveIntegerField()),
                ('garage', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('is_south_facing', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='../default_property_gbwuvw', upload_to='images/')),
                ('sold', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
